### ISSUE TITLE
Issue: "start" script not found

### ISSUE THREAD

**Issue by matt-lio** [Startr/RIAC-Guidebooks#9]
When executing ```bash <(curl -sL startr.sh)```, this issue arises.

<img width="729" alt="Screenshot 2024-07-25 at 11 20 29 AM" src="https://github.com/user-attachments/assets/7506969c-7747-42d2-b74b-bb6e484d250a">

**Comment by matt-lio** [comment]
Solution: "serve" script was changed to "start" in ```package.json```. 
<img width="667" alt="Screenshot 2024-07-25 at 11 21 54 AM" src="https://github.com/user-attachments/assets/92734e31-f3d5-4580-92fb-f9ca875760bc">

**Comment by opencoca** [comment]
Resolved in https://github.com/Startr/RIAC-Guidebooks/commit/87dc4fe341669a6c7e9b500b2db119231fbae77d 

That being said we're still intermittently hitting:

```
[10:07:30] The following tasks did not complete: serve, <series>, copyToDist
[10:07:30] Did you forget to signal async completion?
```

The fix for this is likely to implement https://gulpjs.com/docs/en/getting-started/async-completion/
